// <auto-generated />
using Lab789HRWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab789HRWebApi.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20260912140430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab789HRWebApi.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "alex@gmail.com",
                            FullName = "Alex Tran",
                            Position = "Developer",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR",
                            Email = "john.doe@gmail.com",
                            FullName = "John Doe",
                            Position = "HR Manager",
                            Salary = 1500m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Finance",
                            Email = "jane.smith@gmail.com",
                            FullName = "Jane Smith",
                            Position = "Accountant",
                            Salary = 1200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
